IF (0 = (SELECT snapshot_isolation_state FROM sys.databases WHERE name = DB_NAME())) BEGIN
	ALTER DATABASE CURRENT SET ALLOW_SNAPSHOT_ISOLATION ON
	ALTER DATABASE CURRENT SET READ_COMMITTED_SNAPSHOT ON WITH ROLLBACK AFTER 5 SECONDS

	DECLARE iterator CURSOR FOR
		SELECT '[' + TABLE_SCHEMA + '].[' + TABLE_NAME + ']'
		FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE'
	DECLARE @table VARCHAR(255)
	DECLARE @alter VARCHAR(255)

	OPEN iterator
	FETCH NEXT FROM iterator INTO @table
	WHILE @@FETCH_STATUS = 0 BEGIN
		SET @alter = 'ALTER INDEX ALL ON ' + @table + ' REBUILD';
		EXEC(@alter)
		FETCH NEXT FROM iterator INTO @table 
	END 
 
	CLOSE iterator 
	DEALLOCATE iterator
END
