//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheaterBooking.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TheaterDBEntities : DbContext
    {
        public TheaterDBEntities()
            : base("name=TheaterDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Booking> Booking { get; set; }
        public virtual DbSet<Genre> Genre { get; set; }
        public virtual DbSet<Movie> Movie { get; set; }
        public virtual DbSet<Price> Price { get; set; }
        public virtual DbSet<Rating> Rating { get; set; }
        public virtual DbSet<Screen> Screen { get; set; }
        public virtual DbSet<Showtime> Showtime { get; set; }
        public virtual DbSet<Theater> Theater { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
    }
}
