//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheaterBooking.Web.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Ticket_ID { get; set; }
        public int Booking_ID { get; set; }
        public int Showtime_ID { get; set; }
        public int Price_ID { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Price Price { get; set; }
        public virtual Showtime Showtime { get; set; }
    }
}
